// Code generated by ormtool. DO NOT EDIT.
package model

type Question struct {
	Id        int    `json:"id"`
	Title     string `json:"title"` // 标题
	CreatedAt int    `json:"created_at"`
}

func (*Question) TableName() string {
	return "question"
}

var QuestionCol = struct {
	Id        string
	Title     string
	CreatedAt string
}{
	Id:        "id",
	Title:     "title",
	CreatedAt: "created_at",
}
