// Code generated by ormtool. DO NOT EDIT.
package model

type User struct {
	Id        int    `json:"id"`
	NickName  string `json:"nick_name"`
	Mobile    string `json:"mobile"` // 手机号
	OpenId    string `json:"open_id"`
	Auth      string `json:"auth"`
	CreatedAt int    `json:"created_at"`
	UpdatedAt int    `json:"updated_at"`
	DeletedAt int    `json:"deleted_at"`
}

var UserCol = struct {
	Id        string
	NickName  string
	Mobile    string
	OpenId    string
	Auth      string
	CreatedAt string
	UpdatedAt string
	DeletedAt string
}{
	Id:        "id",
	NickName:  "nick_name",
	Mobile:    "mobile",
	OpenId:    "open_id",
	Auth:      "auth",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
}
